name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }} # example: hello.world

        SERVER_FILE: dockerfiles/server/Dockerfile

        PLATFORM_AMD64: linux/amd64
        IMAGE_TAG_SERVER_AMD64: latest-server-amd64

        PLATFORM_ARM64: linux/arm64/v8
        IMAGE_TAG_SERVER_ARM64: latest-server-arm64
      run: |
        
        docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SERVER_AMD64 . --file $SERVER_FILE --platform $PLATFORM_AMD64
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SERVER_AMD64
        
        docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SERVER_ARM64 . --file $SERVER_FILE --platform $PLATFORM_ARM64
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SERVER_ARM64
